# Generated by Django 4.1.3 on 2022-12-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
    ]
