# Generated by Django 4.1.3 on 2022-12-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_fund_user_remove_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fund',
            name='qualification',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=500),
        ),
    ]
