# Generated by Django 4.1.3 on 2022-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_fund_user_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='applied',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='remindtoapply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='remindtoapply',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
