# Generated by Django 4.1.3 on 2022-12-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_fund_applied_fund_remindtoapply_job_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.CharField(max_length=100, null=True)),
                ('remindtoapply', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fund',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='remindtoapply',
        ),
        migrations.RemoveField(
            model_name='job',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remindtoapply',
        ),
    ]
